/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Operaciones.Conector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Videla Araya
 */
public class Salidas extends javax.swing.JInternalFrame {

    Buscar_salidas buscarsalidas;
    DefaultTableModel modeloTablaSalidas = new DefaultTableModel();
    int Item = 1;
    int documento = 0;

    /**
     * Creates new form Salidas
     */
    public Salidas() {
        initComponents();

        modeloTablaSalidas.addColumn("Item");
        modeloTablaSalidas.addColumn("Código");
        modeloTablaSalidas.addColumn("Detalle");
        modeloTablaSalidas.addColumn("Cantidad");
        modeloTablaSalidas.addColumn("Unidad");
        modeloTablaSalidas.addColumn("Solicitante");

    }

    public boolean camposVacios() {
        boolean r = this.sldFecha.getDate() == null;
        r |= this.sldSpinner.getValue() == null;
        r |= this.txtsldSolicitante.getText().isEmpty();

        return r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sldFecha = new com.toedter.calendar.JDateChooser();
        lblEquipo = new javax.swing.JLabel();
        sldCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblSolicitante = new javax.swing.JLabel();
        txtsldSolicitante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsldCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsldDetalle = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsldCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsldUnidad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnsldAgregar = new javax.swing.JButton();
        btnsldGuardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        sldSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        sldTabla = new javax.swing.JTable();

        setTitle("Salida de materiales en faena");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orbit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Fecha");

        sldFecha.setNextFocusableComponent(sldCombo);

        lblEquipo.setText("Equipo");

        sldCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UE-58", "UE-59", "UE-60", "OPERACIONES", "MANTENIMIENTO", "HSEC", "RR.HH", "OTRO" }));
        sldCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sldComboItemStateChanged(evt);
            }
        });

        jLabel4.setText("Documento de salida Nº");

        lblSolicitante.setText("Nombre del solicitante");
        lblSolicitante.setEnabled(false);

        txtsldSolicitante.setEnabled(false);
        txtsldSolicitante.setNextFocusableComponent(txtsldCodigo);

        jLabel6.setText("Código");

        txtsldCodigo.setNextFocusableComponent(txtsldDetalle);

        jLabel7.setText("Detalle");

        txtsldDetalle.setNextFocusableComponent(txtsldCantidad);
        txtsldDetalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsldDetalleFocusGained(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar2.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar2Roll.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Cantidad");

        txtsldCantidad.setNextFocusableComponent(txtsldUnidad);

        jLabel9.setText("Unidad");

        txtsldUnidad.setNextFocusableComponent(btnsldAgregar);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnsldAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AgregarNormal.png"))); // NOI18N
        btnsldAgregar.setBorderPainted(false);
        btnsldAgregar.setRolloverEnabled(true);
        btnsldAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/AgregarRoll.png"))); // NOI18N
        btnsldAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsldAgregarActionPerformed(evt);
            }
        });

        btnsldGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuardarNormal.png"))); // NOI18N
        btnsldGuardar.setBorderPainted(false);
        btnsldGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/GuardarRoll.png"))); // NOI18N
        btnsldGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsldGuardarActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CerrarNormal.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setRolloverEnabled(true);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CerrarRoll.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnsldAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsldGuardar)
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnsldGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnsldAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsldUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEquipo)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sldCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(lblSolicitante)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtsldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsldDetalle))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(sldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sldSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sldFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sldSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSolicitante)
                        .addComponent(txtsldSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sldCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtsldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsldDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtsldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtsldUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        sldTabla.setBackground(new java.awt.Color(204, 204, 204));
        sldTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Código", "Detalle", "Cantidad", "Unidad", "Solicitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sldTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Escritorio.FormularioIniciado = false;
        Escritorio.nocode = false;
        Escritorio.Escritorio.removeAll();
        Escritorio.Escritorio.updateUI();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Escritorio.bsalidas == false) {
            Escritorio.bsalidas = true;
            buscarsalidas = new Buscar_salidas();
            Escritorio.Escritorio.add(buscarsalidas);
            buscarsalidas.toFront();
            buscarsalidas.setVisible(true);
            buscarsalidas.setLocation(650, 0);
        }
        //quite Else
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsldDetalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsldDetalleFocusGained
        // TODO add your handling code here:
        Conector con = new Conector();
        con.connect();
        ResultSet rs = null;
        int Id;
        int Tipo;
        int caso = 0;
        String codigo = this.txtsldCodigo.getText();
        String sql = "SELECT Id, Descripcion, Unidad, Tipo FROM Maestro WHERE Codigo ='" + codigo + "'";
        rs = con.buscar(sql);
        try {
            if (!rs.next()) {
                caso = 1;
                this.txtsldDetalle.setText("CODIGO NO ARROJA RESULTADOS!!!");
                this.txtsldCodigo.requestFocus();
            } else {
                caso = 2;
                Id = rs.getInt("Id");
                Tipo = rs.getInt("Tipo");
                System.out.print("Familia material "+Tipo);
                Escritorio.idData[0] = Id;
                this.txtsldDetalle.setText(rs.getString("Descripcion"));
                this.txtsldUnidad.setText(rs.getString("Unidad"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Salidas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtsldDetalleFocusGained

    private void sldComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sldComboItemStateChanged
        // TODO add your handling code here:
        int opcion = sldCombo.getSelectedIndex();
        if (opcion == 7) {
            Salidas.txtsldSolicitante.setEnabled(true);
            Salidas.lblSolicitante.setEnabled(true);
            Salidas.lblEquipo.setEnabled(false);
            Salidas.sldCombo.setEnabled(false);

        }
    }//GEN-LAST:event_sldComboItemStateChanged

    private void btnsldAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsldAgregarActionPerformed
        // TODO add your handling code here:
        int cantidad = 0;
        String solicitante = "";
        documento = (int) sldSpinner.getValue();
        String codigo = txtsldCodigo.getText();
        String detalle = txtsldDetalle.getText();
        String unidad = txtsldUnidad.getText();
        try {
            cantidad = Integer.parseInt(txtsldCantidad.getText());
        
        if (sldCombo.isEnabled()) {
            solicitante = (String) sldCombo.getSelectedItem();
        } else {
            solicitante = txtsldSolicitante.getText();
        }
        modeloTablaSalidas.addRow(new Object[]{Item, codigo, detalle, cantidad, unidad, solicitante});

        sldTabla.setModel(modeloTablaSalidas);

        Item++;
        txtsldCodigo.setText("");
        txtsldDetalle.setText("");
        txtsldCantidad.setText("");
        txtsldUnidad.setText("");
        txtsldCodigo.requestFocus();
         } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(null, "No pueden quedar campos vacios", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            txtsldCantidad.requestFocus();
        }

    }//GEN-LAST:event_btnsldAgregarActionPerformed

    private void btnsldGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsldGuardarActionPerformed
        // TODO add your handling code here:

        txtsldCodigo.setText("");
        txtsldDetalle.setText("");
        txtsldCantidad.setText("");
        txtsldUnidad.setText("");
        txtsldCodigo.requestFocus();

        documento++;
        modeloTablaSalidas.setRowCount(0);
        Item = 1;

        Salidas.sldSpinner.setValue(documento);
        Salidas.txtsldSolicitante.setEnabled(false);
        Salidas.lblSolicitante.setEnabled(false);
        Salidas.lblEquipo.setEnabled(true);
        Salidas.sldCombo.setEnabled(true);
        txtsldCodigo.requestFocus();
    }//GEN-LAST:event_btnsldGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsldAgregar;
    private javax.swing.JButton btnsldGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblEquipo;
    public static javax.swing.JLabel lblSolicitante;
    public static javax.swing.JComboBox<String> sldCombo;
    public static com.toedter.calendar.JDateChooser sldFecha;
    public static javax.swing.JSpinner sldSpinner;
    private javax.swing.JTable sldTabla;
    public static javax.swing.JTextField txtsldCantidad;
    public static javax.swing.JTextField txtsldCodigo;
    public static javax.swing.JTextField txtsldDetalle;
    public static javax.swing.JTextField txtsldSolicitante;
    public static javax.swing.JTextField txtsldUnidad;
    // End of variables declaration//GEN-END:variables
}
